### ISSUE TITLE
Logo _proposal_ for ThePiano project

### ISSUE THREAD

**Issue by tjulises** [stefan50/ThePiano#3]
Hi @stefan50 ,

My name is Ulises or TJ if you like,
i'm a graphic designer and I contribute to cool projects (_open source_) like this one!
if this is something that you're looking forward to, I'll gladly upload some logo proposals

I'll look forward for your reply, cheers!

TJ.

**Comment by stefan50** [comment]
Hi, @tjulises ,

We would love to receive your support, of course. Here is my email - ste.angelov.tues19@gmail.com. Should you send any designs, please do so to my email. 

Best regards,
Stefan Angelov, developer

**Comment by tjulises** [comment]
It can't be discussed through this issue, so it's a public conversation @stefan50 ?

I can upload the first proposal when ready, and I'll tag you in it so you know it's ready...

I'll look forward for your reply, thanks!

I'd also like to ask some questions (towards the logo-making)

What's the name that should be displayed on the logo, If there should be any.

How would you describe this project,
what is it intended to do?

What would you like this logo to transmit?

this little details are going to help me transmit what it's supposed to.

I'll look forward for your reply, cheers!

**Comment by momchiltues19** [comment]
@tjulises hi, I'm the other developer that is working on this project. 

We talked about the logo and decided, that it shouldn't have text and that it should promptly feature a piano or notes or something along those lines, as this project is a piano-based RPG.

Thank you again so much for offering us your help, I look forward to seeing your first suggestion.

**Comment by tjulises** [comment]
Hello @momchiltues19 ,
I'm really excited on how the logo turned out,
By the different color variation it trying to say that it can be in any color you want it to be,
I can change anything according to your desires, I hope you like it!
![piano](https://user-images.githubusercontent.com/39039587/40870986-71d072ae-6601-11e8-991a-8d65f2d4bd43.png)

**Comment by momchiltues19** [comment]
@tjulises,

Wow! The logos really did turn out amazing! 

Personally, I find 1,5 and 6 to be the best ones. The colours are very fitting to the theme of the game, although purple should maybe be more prominently displayed in the logo as the game takes place in a purple cave. 

Also, the logo should have a retro feel to it as the game is an 8bit RPG with classic Pokémon-esque graphics.

Once again, you did an awesome job and I can't wait what you would suggest next!

**Comment by tjulises** [comment]
@stefan50 

The left column designs were the older (choosen) ones and the right column its the updated version, I made purple more visible, Hope you like it!

![sin titulo-1x](https://user-images.githubusercontent.com/39039587/40888942-c4935aa2-672c-11e8-8caf-26c9e79aa491.jpg)

**Comment by stefan50** [comment]
Hi again, @tjulises !

Thanks for the designs! We confered and decided that the design which suits our needs most is number 6, old version! We would love if you would send us a PNG and an ICO of the logo you made, of course with the due credit in the readme! It was a pleasure working with you!

Best regards!

**Comment by tjulises** [comment]
Great @stefan50 ,
I'll let you know when I have made the pull request, I'll upload the ready to use versions, monochromatics in a google drive for any future updates...
thank YOU for letting me be a part of this really cool project, has been a pleasure to me too. :+1:

**Comment by tjulises** [comment]
Thanks again @stefan50 the pull request has been made, the [google drive](https://drive.google.com/open?id=1J93_RZ4oIlMdJeKvQv1bkzleC-_ypkPD) link has been given and everything is merged already so therefore I'll close this issue,

If you could hand me a link to see the logo when it has been updated, it would be nice :+1: 

Best Regards.
-TJ.
